version: 2

jobs:
  build:
    docker:
      - image: nixos/nix:latest
    working_directory: ~/PyF
    steps:
      - checkout
      - run:
          name: Build (Cabal+nix)
          command: nix-build -A pyf-sdist
      - run:
          name: Build (Stack+nix)
          command: nix-shell -p stack --run 'stack test'
