version: 2

jobs:
  nix:
    docker:
      - image: nixos/nix:latest
    working_directory: ~/PyF
    steps:
      - checkout
      - restore_cache:
          keys:
            - cci-nix-{{ checksum "nixpkgs.nix" }}-{{ checksum "default.nix" }}-{{ checksum "PyF.cabal" }}-{{ epoch }}
            - cci-nix-{{ checksum "nixpkgs.nix" }}-{{ checksum "default.nix" }}-{{ checksum "PyF.cabal" }}
            - cci-nix-{{ checksum "nixpkgs.nix" }}-{{ checksum "default.nix" }}
            - cci-nix-{{ checksum "nixpkgs.nix" }}
      - run:
          name: Check hlint
          command: nix-build -A hlint
      - run:
          name: Build current GHC (8.8)
          command: nix-build -A pyf
      - run:
          name: Build GHC 8.6
          command: nix-build -A pyf_86
      - run:
          name: Build GHC 8.10
          command: nix-build -A pyf_810
      - run:
          name: Check ormolu
          command: nix-build -A ormolu
      - save_cache:
          when: always
          name: Cache Dependencies
          key: cci-nix-{{ checksum "nixpkgs.nix" }}-{{ checksum "default.nix" }}-{{ checksum "PyF.cabal" }}-{{ epoch }}
          paths:
            - "/nix/store"

  stack:
    docker:
      - image: fpco/stack-build:lts
    working_directory: ~/PyF
    steps:
      - checkout
      - restore_cache:
          keys:
            - cci-demo-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "PyF.cabal" }}--{{ epoch }}
            - cci-demo-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "PyF.cabal" }}
            - cci-demo-haskell-v1-{{ checksum "stack.yaml" }}
            - cci-demo-haskell-v1
      - run:
          # see: https://github.com/commercialhaskell/stackage/issues/4783
          # `ghc-lib-parser` conflicts with `template-haskell` for module Language.Haskell.TH.Syntax
          # The test suite uses a bare GHC (with all the provided
          # packages). This is fine in nix, but does not work in the
          # stackage CI context where GHC comes with a world of
          # packages.
          # This is here to ensure that it will continue to work in stack CI.
          name: Trash the environment
          command: stack install ghc-lib-parser
      - run:
          name: Build 8.8
          command: stack test
      - run:
          name: Build 8.6
          command: stack --resolver lts-14.27 test
      - save_cache:
          when: always
          name: Cache Dependencies
          key: cci-demo-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "PyF.cabal" }}--{{ epoch }}
          paths:
            - "/root/.stack"
            - ".stack-work"

workflows:
  version: 2
  nix_stack:
    jobs:
      - nix
      - stack
