name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: guibou
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    # Linters
    - name: Check hlint
      run: nix-build -A hlint
    - name: Check ormolu
      run: nix-build -A ormolu

    # Builds
    - name: Build current GHC - 8.8
      run: nix-build -A pyf
    #- name: Build GHC 8.6
    #  run: nix-build -A pyf_86
    #- name: Build GHC 8.10
    #  run: nix-build -A pyf_810
